flatpak/libportal

- libportal/filechooser.c
FileCall::method is only assigned from static strings, so does not
need to be free'ed.
> Remove uneeded free

- libportal/account.c
- libportal/background.c
- libportal/email.c
- libportal/filechooser.c
- libportal/inhibit.c
- libportal/location.c
- libportal/openuri.c
- libportal/portal-gtk3.h
- libportal/portal-gtk4.h
- libportal/portal-helpers.h
- libportal/print.c
- libportal/remote.c
- libportal/screenshot.c
- libportal/updates.c
- libportal/utils.c
- libportal/wallpaper.c
In C++, name "export" is a keyword and using libportal in a C++ applications fails to build because of that.
> XdpParent: rename export and unexport to avoid collision with keywords

- libportal/background.c
- libportal/updates.c
g_print() is problematic for library users that have machine-readable
output like TAP or JSON on stdout, whereas the g_log() family are
easy to divert to stderr in such cases.
> Convert some debug printfs into g_debug()

- portal-test/portal-test-win.c
Other portal-test users don't have the maintainer's home directory,
so use a path that developers are somewhat likely to have.
> Use a GNOME background to test setting wallpaper

- libportal/meson.build
g_hash_table_steal_extended() is new in glib 2.58.
Closes: #16
> build: Bump required glib version

- libportal/openuri.c
When user specifies to open a file with write access, we need to open it with specified permission, otherwise xdg-desktop-portal will fail as it checks for write access.
Also follow glib and do not use O_PATH, because since xdg-desktop-portal 1.0.1, regular file descriptors are also accepted.
For reference:
1) [Glib change](https://gitlab.gnome.org/GNOME/glib/-/commit/e244a78fbcbba3ab116f5a62f724a8f6cd926570)
2) [Portal bug](https://github.com/flatpak/xdg-desktop-portal/issues/167)
> OpenURI: open file with write access when requested

- libportal/portal-gtk4.h
(Untested)
Since [1] this was changed to GdkToplevel API, adapt the header to use it.
[1] http://gitlab.gnome.org/GNOME/gtk/commit/3023a61e1d65bee1db3def19ddacf328ad4b6c90
> gtk4: Use GdkToplevel to export and unexport

- libportal/portal-helpers.h
xdp_parent_free() was calling g_object_unref() at the
'data' field of _XdpParent, but the actual GObject field
is 'object'.
Unref the correct field, 'object', instead of the 'data'
field.
> portal-helpers: Unref correct object

- portal-test/portal-test-win.c
- portal-test/portal-test-win.ui
Opens the directory of a file opened via the document portal.
For testing https://github.com/flatpak/xdg-desktop-portal/pull/552.
> portal-test: Add OpenURI directory button

- .github/workflows/build.yml
Copy-pasting [1]. This fixes the pre-build step.
[1] https://github.com/flatpak/flatpak-builder/commit/1898b36d1fae6f011e5465982154e18320549470
> CI: Add mono apt repository

- libportal/meson.build
- libportal/remote.c
- libportal/remote.h
- portal-test/gtk3/portal-test-win.c
- portal-test/gtk4/portal-test-win.c
There currently is no way to pass a cursor mode when creating
a screencast / remote desktop session, which is pretty limiting.
Add XdpCursorMode, and the corresponding parameters to the session
functions.
> [API Break] Add cursor mode to remote APIs

- README.md
Based on #29, but a bit expanded and hopefully addressing concerns on that PR. Omits docs instructions for now as I'm not familiar with how that works.
> README: Add 'Getting started' directions

- README.md
> README: use `portal-tests` option in examples

- .github/workflows/build.yml
- .github/workflows/flatpak.yml
- build-aux/org.gnome.PortalTest.Gtk3.json
- build-aux/org.gnome.PortalTest.Gtk4.json
- build-aux/org.gnome.PortalTest.Qt5.json
Generate Flatpak bundles for all manifests we have in-tree.
Cleanup and increment the builds to include:
* Ubuntu 20.04
* Ubuntu 21.10
* Fedora 35
> Flatpak & CI improvements

- portal-test/gtk4/window.js
Streams may not have (x, y), and we need to account for that.
This fixes stream sizes not showing up when selecting windows
to screencast on GNOME.
> portal-tests/gtk4: Carefully parse streams

- .gitignore
- build-aux/build.sh
Previously this convenience script only built the Gtk3 version.
> build-aux/build.sh: Build all manual tests as Flatpak apps

- libportal/remote.h
This is supported by the ScreenCast portal now, so reflect this in the API.
> remote: Add support for VIRTUAL sources

- libportal/portal-private.h
- libportal/remote.c
- libportal/remote.h
- libportal/session-private.h
- libportal/session.c
- portal-test/gtk3/portal-test-win.c
- portal-test/gtk4/window.js
Add the XdpPersistMode enum, and modify the signature of
xdp_portal_create_screencast_session() to account for the
persist mode, and the restore token.
Add getters of the restore token and the persist mode to
XdpSession, and document that they are only available after
starting the session.
Adjust the corresponding code of portal tests. Make the GTK4
portal test exercise the transient persist mode.
> Screencast session restore

- libportal/remote.c
This is what the portal documents to use, and is what every implementation expects.
> remote: Pass "types" instead of "type" to remote desktop

- libportal/camera.c
The `org.freedesktop.DBus.Properties.Get()` method always returns a
variant of type `(v)`, no matter what the actual type of the property
is.
Before this commit, `xdp_portal_is_camera_present()` was broken, as it
outputted CRITICALs on each call, since the variant type was wrong.
> camera: Use correct variant for is_camera_present()

- meson_options.txt
Ever since the option was renamed from `gtk_doc` to `docs`, the
API reference is not built with gtk-doc :-)
> build: Correct option description

- libportal/portal.c
Passing FALSE (zero) to g_once_init_leave() isn't allowed and leads to
GLib-CRITICAL **: 22:02:50.836: g_once_init_leave: assertion 'result !=0' failed
So rework xdp_portal_running_under_flatpak() a bit.
> Avoid a critical in the sandbox check code

- libportal/portal-qt5.cpp
- libportal/portal-qt5.h
This will be useful in xdp_portal_open_file() where 'current_filter' option expects just one filter and not a list.
> libportal-qt: make filechooserFilterToGVariant() public

- libportal/account.c
- libportal/background.c
- libportal/camera.c
- libportal/email.c
- libportal/filechooser.c
- libportal/inhibit.c
- libportal/location.c
- libportal/openuri.c
- libportal/print.c
- libportal/remote.c
- libportal/screenshot.c
- libportal/wallpaper.c
Currently, for most portals, we cancel the callback for the task's
GCancellable in the response_received() function, which is reached when
the method call was successful. However when the method call was not
successful, the call_returned() or similar function is reached, and we call
g_task_return_error() without disconnecting the cancellable_cb(). This
is an issue because the application code using libportal may decide to
call g_cancellable_cancel() on its GCancellable as part of cleaning up
state after the portal call fails, and this would lead to us returning
the task twice, causing a critical warning (from GLib's g_return_if_fail
(!task->ever_returned);) and a seg fault when we try to free the already
freed Call data.
This happens because even though we already call the free function …
> Ensure GCancellable callback is cancelled

- .github/workflows/build.yml
We have a predefined variable for it, let's use it
This also fixes the current issues with the `check-abi` job - new git is unhappy about the owner of the cloned repository
cc @hadess
> ci: use the predefined env var for the git sha

- libportal/wallpaper.c
The C code allows for it to be NULL, let's make this in the bindings too
so we don't have to instantiate windows to test this.
> wallpaper: annotate the parent window as nullalble

- .github/workflows/build.yml
- libportal/portal.c
- tests/gir-testenv.sh
- tests/meson.build
- tests/pyportaltest/__init__.py
- tests/pyportaltest/templates/__init__.py
- tests/pyportaltest/templates/wallpaper.py
- tests/pyportaltest/test_wallpaper.py
Using python and dbusmock makes it trivial to add a large number of
tests for libportal only, without requiring an actual portal
implementation for the Portal interface to be tested.
Included here is the wallpaper portal as an example, hooked into meson test.
A helper script is provided too for those lacking `meson devenv`,
```
$ ./test/gir-testenv.sh
$ cd test
$ pytest --verbose --log-level=DEBUG [... other pytest arguments ...]
```
The test setup uses dbusmock interface templates (see
pyportaltest/templates) to handle the actual DBus calls.
Because DBus uses a singleton for the session bus, we need libportal to
specifically connect to the address given in the environment - otherwise
starting mock dbus services has no effect.
This test suite depends on [dbusmock commit 4a191d8ba293: …
> test: add a pytest/dbusmock-based test suite

- libportal/notification.c
- libportal/portal.c
- libportal/spawn.c
- libportal/updates.c
- meson.build
- portal-test/gtk3/portal-test-win.c
cc @mwleeds for the cgroup hierarchies, `!strcmp() != 0` was sufficiently confusing that I'm going to punt this to you :smile: but based on the comment above, `g_str_equal()` should be the correct replacement.
> Up the warning level and fix the resulting warnings

- libportal/portal-private.h
- libportal/portal.c
For debugging it's useful to run against a bus that doesn't require
replacing the real xdg-desktop-portal. Make this possible by setting
the LIBPORTAL_PORTAL_BUS_NAME environment variable.
> Allow overriding the bus name we connect to

- .github/workflows/build.yml
- README.md
- build-aux/org.gnome.PortalTest.Gtk3.json
- build-aux/org.gnome.PortalTest.Gtk4.json
- build-aux/org.gnome.PortalTest.Qt5.json
- libportal/meson.build
- meson.build
- meson_options.txt
- portal-test/meson.build
- tests/meson.build
This changes the 'backends' option to the special string 'auto' - all
backends become optional by default and are built if the dependencies
are available.
If need be this can be combined with explicitly listing a backend, so
backends=auto,gtk3 will require the GTK3 backend and optionally build
the Qt5 and GTK4 backends. A summary is printed to list the actually
enabled backends and a warning where no backends are enabled at all.
This makes life easier for new users since the majority of them will not
have GTK3, GTK4 and Qt5 headers installed by default and thus are almost
guaranteed to run into a meson error on first configure.
Fixes https://github.com/flatpak/libportal/issues/94
> meson: default the backends list to 'auto'

- .github/workflows/build.yml
- .github/workflows/flatpak.yml
Node 12 is deprecated so let's bump the actions to newer versions that use Node 16. See 
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
> CI: bump some actions to newer versions

- libportal/portal-helpers.h
- libportal/portal.c
Fix issue #118
Adds `xdp_portal_initable_new` as an alterative to `xdp_portal_new` that can return a GError.
I used https://gitlab.gnome.org/GNOME/glib/-/blob/main/gio/gcharsetconverter.c as a reference to see how to implement the `GInitable` interface.
> portal: use GInitable to enable init error propagation

- libportal/openuri.c
Don't leak GVariantBuilder state when an error is encountered.
> libportal: clear unused variant builder

- .github/workflows/flatpak.yml
- Bump `flatpak-builder` to `v6`.
- Bump GNOME container image to `44`.
> flatpak.yml: bump actions version, container image

- libportal/portal-private.h
- libportal/remote.c
- libportal/remote.h
- libportal/session-private.h
- tests/pyportaltest/templates/remotedesktop.py
- tests/pyportaltest/test_remotedesktop.py
- tests/pyportaltest/test_screencast.py
See https://github.com/flatpak/xdg-desktop-portal/pull/762
This adds support for connecting a remote desktop/screen cast session to an [EIS implementation](https://gitlab.freedesktop.org/libinput/libei/) so the application and the EIS implementation (i.e. the compositor) can talk directly without having to bounce DBus messages through the portal.
cc @jadah, @ofourdah
> Support RemoteDesktop.ConnectToEIS

- libportal/portal-private.h
- libportal/portal.c
Calling `g_object_new()` for an XdpPortal used to work before 0.7, but no longer sets up the GDBusConnection, making most method calls fail with `assertion 'G_IS_DBUS_CONNECTION (connection)' failed`. This makes #119 an incompatible change.
In particular, the GTK 4 test app calls `new Xdp.Portal()`, which is a JavaScript binding for `g_object_new()` and fails in this way. GObject documentation suggests that bindings should automatically detect types that implement GInitable and call GInitable.init in the higher-level language's constructor, but it seems that neither gjs nor pygobject actually does this.
Mostly preserve previous functionality by moving the actual initialization back to the GObject instance init function, and making the GInitable init function just report a pre-existing …
> Restore ability to call g_object_new (XDP_TYPE_PORTAL, ...)

- .github/workflows/build.yml
- .github/workflows/flatpak.yml
- README.md
- build-aux/build.sh
- build-aux/org.gnome.PortalTest.Qt5.json
- build-aux/org.gnome.PortalTest.Qt6.json
- libportal/meson.build
- libportal/portal-qt6.cpp
- libportal/portal-qt6.h
- meson.build
- meson_options.txt
- portal-test/qt5/meson.build
- portal-test/qt6/main.cpp
- portal-test/qt6/meson.build
- portal-test/qt6/portal-test-qt.cpp
- portal-test/qt6/portal-test-qt.h
- portal-test/qt6/portal-test-qt.ui
- tests/meson.build
- tests/qt5/meson.build
- tests/qt6/meson.build
- tests/qt6/test.cpp
- tests/qt6/test.h
Introduce a new libportal-qt6 library with Qt6-specific parent window exports. It contains a blank header with a single function declaration (xdp_parent_new_qt), and explicitly depends on Qt6.
This is based on the existing code for libportal-qt5.
Related: https://github.com/flatpak/libportal/issues/12
> Introduce libportal-qt6

- libportal/remote.c
- libportal/remote.h
- tests/pyportaltest/test_remotedesktop.py
Same as the ScreenCast API
Fixes #127
cc @jadahl
Marking as Draft until I've sold off the right to rename this to a more sensible function name to the highest bidder. Any suggestions?
> remote: Add API to allow for persistence on RemoteDesktop sessions

- libportal/background.c
Ran into this while working on a Vala project. Code contains an explicit null check on it, so this seems to be an intended possibility.
> background: annotate commandline as nullable

- portal-test/gtk3/meson.build
If we define a run_target, Meson assumes that it's functionally necessary and will refuse to configure without an exe_wrapper if cross-compiling. This particular run_target is just for convenience, so skip it if we're cross-compiling and don't have an exe_wrapper available.
---
For context, I've been experimenting with cross-compiling packages in the GNOME ecosystem in Debian, and I found libportal to be a convenient example because it's small and quick to compile while also being reasonably complicated (multiple libraries, GTK 3/4, Qt, GObject-Introspection, Vala binding).
> portal-test/gtk3: Don't provide a run target if we cannot run it

- tests/pyportaltest/__init__.py
DBusTestCase.start_session_bus() is a class method, and can only be called once per class, because DBusTestCase.tearDownClass() will only clean up one session bus. In older versions of dbusmock, calling it more than once will result in dbus-daemon processes being leaked; since 0.30.0, calling it more than once will result in an assertion failure.
Resolves: https://github.com/flatpak/libportal/issues/136  
Bug-Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1058245
> pyportaltest: Only create one session bus per DBusTestCase subclass

- tests/pyportaltest/test_inputcapture.py
I believe removing the first setup_daemon call is the proper fix. Could you confirm?
---
Remove the first DBus daemon_setup call. The create_session_with_barriers will calls setup_daemon on its own.
An assert is triggered in DBusmock by the second setup_daemon call in create_session_with_barriers:
(...)
>       setup = self.create_session_with_barriers(params)
pyportaltest/test_inputcapture.py:481:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ pyportaltest/test_inputcapture.py:59: in create_session_with_barriers
self.setup_daemon(params)
pyportaltest/__init__.py:108: in setup_daemon
self.p_mock, self.obj_portal = self.spawn_server_template(
/usr/lib/python3/dist-packages/dbusmock/testcase.py:438: in spawn_server_template
server = …
> RFC: tests: fix duplicate daemon spawning in inputcapture tests

- build-aux/org.gnome.PortalTest.Gtk3.json
- build-aux/org.gnome.PortalTest.Gtk4.json
- build-aux/org.gnome.PortalTest.Qt5.json
- build-aux/org.gnome.PortalTest.Qt6.json
* build-aux: Explicitly disable backends other than the one we want
Otherwise, building in the GNOME SDK will automatically enable both
Gtk3 and Gtk4 in both apps, even though we wanted each one to have only
the selected toolkit.
* build-aux: Update to current GNOME SDK
> Improve convenience scripts for building demos as Flatpak apps

- libportal/meson.build
There's a build race when building the GTK vapi files:
FAILED: libportal/libportal-gtk4.vapi
error: Package `libportal' not found in specified Vala API directories or GObject-Introspection GIR directories
This can be verified by adding "sleep 10;" to the command for the libportal/libportal.vapi target in the generated build.ninja file.
The GTK vapi files need to have access to the generic libportal.vapi file, but there is no explicit dependency.  Switch the dependency name 'libportal' to the dependency object libportal_vapi so that Meson generates the dependency correctly.
> meson.build: fix build race when building GTK vapi files

- libportal/remote.c
xdp_portal_create_screencast_session fails if the RemoteDesktop interface is unavailable, which is currently the case on all wlroots-based compositors. xdp_portal_create_screencast_session queries the version of the RemoteDesktop interface despite this interface not beings used in the screencast session. Likewise,
xdp_portal_create_remote_desktop_session queries the version of the ScreenCast interface despite this interface not being used in the remote desktop session. This commit removes the unnecessary version queries.
> remote: fix screencasting on wlroots-based compositors

- .github/workflows/build.yml
- .github/workflows/pages.yml
The Fedora jobs build and deploy documentation twice, and that may be a problem.
Use a dedicated workflow with proper a deploy job. This uses the Github Pages deploy action.
> ci: Add dedicated job for documentation pages

- tests/pyportaltest/test_inputcapture.py
It's only reproducible on `meson dist` for some reason, `meson test` runs fine.
> Fix an Input Capture test failure

- libportal/filechooser.c
- libportal/remote.c
- libportal/screenshot.c
This fixes leaks visible in the portal testing
> g_task_propagate_pointer is transfer-full

- tests/pyportaltest/test_remotedesktop.py
This may or may not fix #166 but ever optimistically we go for the former. 
cc @smcv, @GeorgesStavracas
> pyportaltests: work around potential session close timeout failures

- libportal/notification.c
- libportal/notification.h
- libportal/portal-private.h
- tests/pyportaltest/templates/notification.py
- tests/pyportaltest/test_notification.py
Implement the new portal frontend in libportal https://github.com/flatpak/xdg-desktop-portal/pull/1298
> notification: Implement version2 of the interface

- libportal/notification.c
If the function early-returns (which it currently does not, but that would be a reasonable change to make) then we'd call g_object_unref() on uninitialized stack memory. gcc 14.2.0 in the freedesktop SDK 24.08 warns about this.
It's better to make sure that every autofreed variable is initialized, possibly to NULL.
> notification: Ensure that g_autoptr variable is initialized

- libportal/meson.build
- meson.build
- portal-test/gtk4/meson.build
- portal-test/qt5/meson.build
- portal-test/qt6/meson.build
- tests/qt5/meson.build
- tests/qt6/meson.build
* build: Officially require Meson 0.55.0
In practice the GTK3 backend accidentally required 0.55.0 since 0.8.0,
and nobody seems to have complained or even noticed.
Fixes: f7f3acf5 "portal-test/gtk3: Don't provide a run target if we cannot run it"
* gtk4: Replace deprecated path() method with full_path()
This raises a deprecation warning with newer Meson, and now that we
officially require Meson 0.55.0, we can use it unconditionally.
* build: Never require a C++ compiler for the build architecture
Newer Meson issues a warning if we don't specify whether we plan to
compile code for the build architecture or not when adding a language.
Like most projects, this one doesn't seem to ever compile for the build
architecture, only for the host architecture, so when cross-compiling it
will only …
> Fix some Meson warnings by officially requiring 0.55.0

- libportal/account.c
- libportal/background.c
- libportal/camera.c
- libportal/dynamic-launcher.c
- libportal/email.c
- libportal/filechooser.c
- libportal/inhibit.c
- libportal/inputcapture.c
- libportal/location.c
- libportal/notification.c
- libportal/openuri.c
- libportal/print.c
- libportal/remote.c
- libportal/screenshot.c
- libportal/spawn.c
- libportal/trash.c
- libportal/updates.c
- libportal/wallpaper.c
The `(closure)` annotation should go in the callback parameter, e.g.
`* @callback: (scope async) (closure data): a callback ...`
however gobject-introspection will automatically pick up a parameter called `data` as the parameter of the callback.
Fixes the warnings:
```
[36/45] Generating libportal/Xdp-1.0.gir with a custom command (wrapped by meson to set env)
../libportal/account.c:209: Warning: Xdp: invalid "closure" annotation: only valid on callback parameters
../libportal/background.c:329: Warning: Xdp: invalid "closure" annotation: only valid on callback parameters
../libportal/background.c:399: Warning: Xdp: invalid "closure" annotation: only valid on callback parameters
../libportal/camera.c:218: Warning: Xdp: invalid "closure" annotation: only valid on callback parameters …
```
> Remove (closure) annotations

- libportal/glib-backports.h
- libportal/inputcapture-private.h
- portal-test/qt5/portal-test-qt.h
- portal-test/qt6/portal-test-qt.h
- tests/qt5/test.h
- tests/qt6/test.h
* Use `#pragma once` in all headers that do not already have guards
It's easier to deal with header files when it's unconditionally safe to
include the same header more than once.
In particular the absence of `#pragma once` in `glib-backports.h` caused
a build failure in #191, but only for older GLib releases.
* Qt: Use `#pragma once` instead of traditional single-inclusion guards
This is slightly more efficient, and removes any concerns about whether
we have reused the same macro name for two different headers.
> Use #pragma once

- .gitignore
The pytest-based test suite generates these in tests/pyportaltest/ and tests/pyportaltest/templates/ in the source directory, not the build directory.
> .gitignore: Ignore all __pycache__ directories

- libportal/account.c
- libportal/background.c
- libportal/camera.c
- libportal/dynamic-launcher.c
- libportal/email.c
- libportal/filechooser.c
- libportal/inhibit.c
- libportal/inputcapture.c
- libportal/location.c
- libportal/openuri.c
- libportal/print.c
- libportal/remote.c
- libportal/screenshot.c
- libportal/wallpaper.c
* Fix type used for signal IDs
While trying to investigate #169 I noticed that inputcapture was using
guint instead of the correct gulong for GObject signal IDs, which could
conceivably result in a signal ID being truncated and the wrong signal
being disconnected (although in practice signal IDs are allocated
starting from 0, so this is unlikely). The same pattern is seen in all
of the other portals.
Using the correct type also allows g_clear_signal_handler() to be used,
for idempotent signal disconnections.
* Consistently use g_clear_signal_handler to disconnect GObject signals
This is more concise than writing out equivalent code every time,
and ensures that signal disconnection is idempotent and that the correct
type (gulong) is always used for the signal ID.
> Fix type of signal IDs, make disconnection more obviously correct

- libportal/glib-backports.h
- libportal/inputcapture.c
Best reviewed commit-by-commit.
* glib-backports: Add a backport of g_steal_handle_id()
This is useful when writing idempotent code to unsubscribe from GDBus
signals.
* inputcapture: Factor out call_dispose() from call_free()
This makes call_dispose() idempotent, so that it can be called whenever a
Call has become irrelevant, but without freeing the memory used for the
Call structure itself, which would leave it as a dangling pointer if it
is still in use as the user-data of an async call.
This will be used in a subsequent commit to keep the Call alive via a
circular reference between the GTask and Call while we are still waiting
for a result, and then break the circular reference with call_dispose()
when the Call has reached a resolution, either success or failure.
* inputcapture: …
> inputcapture: Reference-count Call objects

- libportal/meson.build
This is a backport of (a subset of) GLib's API, rather than being part of *our* API. If dependent projects need newer GLib API, they should have a newer GLib dependency or include their own backports.
---
This is technically a small API break, but hopefully nobody is *actually* doing `#include <libportal/glib-backports.h>` (certainly https://codesearch.debian.net/search?q=libportal%2Fglib&literal=1 doesn't find any).
Ideally this would be included in a "feature" release like 0.10.0, rather than a bugfix release like 0.9.2.
> build: Don't install glib-backports.h or pass it to GObject-Introspection

- libportal/portal-qt6.cpp
QGenericUnixServices was renamed to QDesktopUnixServices in Qt 6.9.
Upstream change: https://codereview.qt-project.org/c/qt/qtbase/+/609639
> qt6: fix build against Qt 6.9+

- libportal/portal.h
- libportal/settings.c
- libportal/settings.h
Admittedly, it took me a good 30 minutes to understand why I couldn't use the instance methods for [`Xdp.Settings`](https://libportal.org/class.Settings.html#methods), which required me to dig through libportal's source code and realize that these methods aren't part of `libportal/portal.h`. The solution is to simply include `libportal/settings.h`.
---
* Steps to reproduce: `#include <libportal/portal.h>` (only) and try to call instance methods on `XdpSettings`
* Expected result: can do so
* Actual result: compiler errors because `settings.h` wasn't included
I also wrote a small reproducer: https://github.com/TheEvilSkeleton/Settings-Not-Included/commit/8eb0714a4080f3758a8111428099b406f45a210c
> portal: Include `settings.h` header
